language: ruby
bundler_args: --without development production
rvm:
- 2.1.2
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake db:setup spec
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - david@aske.ws
    on_success: change
    on_failure: always
